# limits
MAX_LOGIN_ATTEMPTS = 5
MAX_RATE_LIMIT = 30
MAX_VOLUME = 150

# defaults
DEFAULT_VOLUME = 80
DEFAULT_PLAYBACK_MODE = "queue"
DEFAULT_AUDIO_OUTPUT = "browser"
DISCOVER_RECENT_LIMIT = 15
DISCOVER_FAVORITES_LIMIT = 15
DISCOVER_CACHED_LIMIT = 15
DISCOVER_FEATURED_ARTISTS_LIMIT = 100
DISCOVER_FEATURED_GENRES_LIMIT = 100
